# Generated by Django 5.1.1 on 2024-09-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoodEntry',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='feelings',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mood',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mood_intensity',
            new_name='stok',
        ),
    ]
